//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PonyMaze.Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MazeService {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MazeService() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PonyMaze.Services.Resources.MazeService", typeof(MazeService).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to automatically.
        /// </summary>
        public static string Automatically {
            get {
                return ResourceManager.GetString("Automatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to east.
        /// </summary>
        public static string East {
            get {
                return ResourceManager.GetString("East", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move accepted.
        /// </summary>
        public static string MoveAccepted {
            get {
                return ResourceManager.GetString("MoveAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to north.
        /// </summary>
        public static string North {
            get {
                return ResourceManager.GetString("North", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to south.
        /// </summary>
        public static string South {
            get {
                return ResourceManager.GetString("South", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to west.
        /// </summary>
        public static string West {
            get {
                return ResourceManager.GetString("West", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong MazeId.
        /// </summary>
        public static string WrongMazeMessage {
            get {
                return ResourceManager.GetString("WrongMazeMessage", resourceCulture);
            }
        }
    }
}
